#pragma once

#include "config_common.h"

#define FORCE_NKRO

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_STARTUP_VAL 100
#define HSV_BACKLIGHT_COLOR HSV_BLUE
#define RGB_COLOR_MODO2 150,220,212
#define HSV_COLOR_MODO2 80,160,255
// #define HSV_COLOR_MODO2 HSV_TEAL
